
services:
  live-trader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-trader
    restart: unless-stopped
    environment:
      # You can also put these in an .env file at the project root
      BINANCE_API_KEY: "${BINANCE_API_LIVE_KEY}"
      BINANCE_API_SECRET: "${BINANCE_SECRET_LIVE_KEY}"
      MATRIX_HOMESERVER: "${MATRIX_HOMESERVER}"
      MATRIX_ACCESS_TOKEN: "${MATRIX_ACCESS_TOKEN}"
      MATRIX_ROOM_ID: "${MATRIX_ROOM_ID}"
      MONGO_URI: "${MONGO_URI:-mongodb://host.docker.internal:27017/}"
      MONGO_DB: "${MONGO_DB:-market_data}"
      MONGO_TRADES_COLL: "${MONGO_TRADES_COLL:-live_trade_logs}"
      TZ: "${TZ:-UTC}"
    volumes:
      - live_trader_state:/app/data
    working_dir: /app
    command: ["python", "live_trader.py"]

volumes:
  live_trader_state:
