apiVersion: 1
datasources:
  - name: ggTraderDB
    type: postgres
    uid: ggTraderDB
    url: host.docker.internal:5433
    database: ggtrader
    user: ggtrader
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
    secureJsonData:
      password: ggtrader
