"""
Standalone Portfolio Analysis & Comparison for ggTrader WFO Results.
Compares different capital allocation strategies on the signals generated by WFO.
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import vectorbt as vbt

# Add src to path
sys.path.append(str(Path(__file__).parent.parent / "src"))

from ggTrader.core.fast_backtest import FastBacktest
from ggTrader.utils.setup import load_data_with_movers

def load_wfo_results(results_dir: str):
    """Load results from a specific WFO run directory."""
    res_path = Path(results_dir) / "run_results.json"
    if not res_path.exists():
        raise FileNotFoundError(f"Could not find run_results.json in {results_dir}")
   
    with open(res_path, 'r') as f:
        data = json.load(f)
   
    # Extract per_coin_results
    # Note: Based on inspection, it's in configuration -> _raw_config -> per_coin_results
    config = data.get("configuration", {})
    raw_config = config.get("_raw_config", {})
    per_coin_results = raw_config.get("per_coin_results", {})
   
    if not per_coin_results:
        # Try top level results if it moved
        per_coin_results = data.get("results", {}).get("per_coin_results", {})
       
    if not per_coin_results:
        raise ValueError("Could not find per_coin_results in JSON")
       
    return per_coin_results, raw_config

def generate_combined_signals(ohlcv, per_coin_results, global_config):
    """Generate entries and exits for all coins using their best WFO parameters."""
    combined_entries = []
    combined_exits = []
    combined_close = []
    symbol_robustness = {}
   
    symbols = list(per_coin_results.keys())
   
    for symbol in symbols:
        if symbol not in ohlcv.columns.get_level_values(0):
            print(f"Warning: Symbol {symbol} not in OHLCV, skipping.")
            continue
           
        res = per_coin_results[symbol]
        best_params = res["best_params"]
        best_strategy = res["best_strategy"]
        best_exit = res["best_exit"]
        symbol_robustness[symbol] = res.get("robustness_score", 0.0)
       
        # Setup engine for this symbol
        config = {
            **global_config,
            "ENTRY_STRATEGY": best_strategy,
            "EXIT_STRATEGY": best_exit,
            "USE_VECTORIZED": False
        }
       
        sym_ohlcv = ohlcv[[symbol]]
        engine = FastBacktest(sym_ohlcv, best_params, config=config)
       
        # We only need the signals
        engine.run(show_progress=False)
       
        # Handle MultiIndex or standard Index
        def _get_single_col(df, sym):
            if isinstance(df.columns, pd.MultiIndex):
                # Look for column where last level is sym
                try:
                    return df.xs(sym, level=-1, axis=1)
                except Exception:
                    # Fallback to first column if symbol not in index
                    return df.iloc[:, [0]]
            else:
                return df[[sym]]

        entries = _get_single_col(engine.entries, symbol)
        exits = _get_single_col(engine.exits, symbol)
        close = sym_ohlcv.xs("close", level=1, axis=1)
       
        # Force column name to symbol
        entries.columns = [symbol]
        exits.columns = [symbol]
        close.columns = [symbol]
       
        combined_entries.append(entries)
        combined_exits.append(exits)
        combined_close.append(close)
       
    return (
        pd.concat(combined_entries, axis=1),
        pd.concat(combined_exits, axis=1),
        pd.concat(combined_close, axis=1),
        symbol_robustness
    )

def run_strategy_equal_share(close, entries, exits, config, share=0.1):
    """Current strategy: flat % per trade with cash sharing."""
    pf = vbt.Portfolio.from_signals(
        close=close.astype(float),
        entries=entries.astype(bool),
        exits=exits.astype(bool),
        init_cash=float(config["START_CASH"]),
        fees=float(config["FEES"]),
        slippage=float(config["SLIPPAGE"]),
        freq=config["FREQ"],
        size=share,
        size_type="percent",
        cash_sharing=True,
        group_by=np.full(close.shape[1], 0)
    )
    # Static weight for all symbols
    weights = pd.DataFrame(share, index=close.index, columns=close.columns)
    return pf, weights

def run_strategy_max_diversified(close, entries, exits, config):
    """Allocate 1/N to every symbol, allowing all signals to be taken."""
    n = close.shape[1]
    pf = vbt.Portfolio.from_signals(
        close=close.astype(float),
        entries=entries.astype(bool),
        exits=exits.astype(bool),
        init_cash=float(config["START_CASH"]),
        fees=float(config["FEES"]),
        slippage=float(config["SLIPPAGE"]),
        freq=config["FREQ"],
        size=1.0 / n,
        size_type="percent",
        cash_sharing=True,
        group_by=np.full(close.shape[1], 0)
    )
    weights = pd.DataFrame(1.0 / n, index=close.index, columns=close.columns)
    return pf, weights

def run_strategy_volatility_weighted(close, entries, exits, config, window=20):
    """Allocate inversely proportional to rolling volatility."""
    # Note: VectorBT's 'size' per trade uses the value *at the time of signal*
    # Calculate rolling std (volatility)
    returns = close.pct_change()
    rolling_vol = returns.rolling(window=window).std().fillna(method='bfill')
   
    # Inverse volatility weights
    inv_vol = 1.0 / rolling_vol
    # For a portfolio, we might want to normalize so sum of all coins is 1.0
    # But for 'size_type=percent' with cash_sharing=True, it's the size *per trade*.
    # If 10 coins have signal, we want them each to take their share.
    # Total share = sum(weights for active coins).
   
    # Simple approach: weight[i] = (1/vol_i) / mean(1/vol for all j) * (1/N)
    # This keeps it in safe range [0.0, 1.0] while favoring low vol coins.
    weights = inv_vol.div(inv_vol.sum(axis=1), axis=0)
   
    # We pass 'weights' as the size array.
    pf = vbt.Portfolio.from_signals(
        close=close.astype(float),
        entries=entries.astype(bool),
        exits=exits.astype(bool),
        init_cash=float(config["START_CASH"]),
        fees=float(config["FEES"]),
        slippage=float(config["SLIPPAGE"]),
        freq=config["FREQ"],
        size=weights,
        size_type="percent",
        cash_sharing=True,
        group_by=np.full(close.shape[1], 0)
    )
    return pf, weights

def run_strategy_robustness_weighted(close, entries, exits, config, robustness_scores):
    """Allocate proportional to WFO robustness score."""
    scores = pd.Series(robustness_scores)
    # Normalize robustness scores to weights [0, 1]
    # Sum to 1.0 logic
    weights = scores / scores.sum()
   
    # Broadcast to DataFrame
    weights_df = pd.DataFrame([weights.values] * len(close), index=close.index, columns=close.columns)

    pf = vbt.Portfolio.from_signals(
        close=close.astype(float),
        entries=entries.astype(bool),
        exits=exits.astype(bool),
        init_cash=float(config["START_CASH"]),
        fees=float(config["FEES"]),
        slippage=float(config["SLIPPAGE"]),
        freq=config["FREQ"],
        size=weights_df,
        size_type="percent",
        cash_sharing=True,
        group_by=np.full(close.shape[1], 0)
    )
    return pf, weights_df

# TODO: Add Risk Parity and Kelly

def run_strategy_benchmark(close, config):
    """Equal-weight buy-and-hold benchmark."""
    n = close.shape[1]
    entries = pd.DataFrame(False, index=close.index, columns=close.columns)
    exits = pd.DataFrame(False, index=close.index, columns=close.columns)
    entries.iloc[0] = True
    exits.iloc[-1] = True
   
    pf = vbt.Portfolio.from_signals(
        close=close.astype(float),
        entries=entries,
        exits=exits,
        init_cash=float(config["START_CASH"]),
        fees=float(config["FEES"]),
        slippage=float(config["SLIPPAGE"]),
        freq=config["FREQ"],
        size=1.0 / n,
        size_type="percent",
        cash_sharing=True,
        group_by=np.full(n, 0)
    )
    return pf

def main():
    parser = argparse.ArgumentParser(description="Portfolio Strategy Analysis Standalone")
    parser.add_argument("--results-dir", type=str, required=True, help="Path to WFO results")
    args = parser.parse_args()
   
    print(f"Loading results from {args.results_dir}...")
    per_coin_results, raw_config = load_wfo_results(args.results_dir)
   
    print("Loading OHLCV data...")
    ohlcv, _ = load_data_with_movers(raw_config)
   
    print("Generating combined signals...")
    entries, exits, close, robustness = generate_combined_signals(
        ohlcv, per_coin_results, raw_config
    )
   
    strategies = {}
    weights = {}
   
    print("Running Baseline (Current: Flat 10%)...")
    strategies["Flat 10%"], weights["Flat 10%"] = run_strategy_equal_share(
        close, entries, exits, raw_config, share=0.1
    )
   
    print("Running Max Diversified (1/N)...")
    strategies["Max Diversified (1/N)"], weights["Max Diversified (1/N)"] = run_strategy_max_diversified(
        close, entries, exits, raw_config
    )
   
    print("Running Volatility Weighted...")
    strategies["Volatility Weighted"], weights["Volatility Weighted"] = run_strategy_volatility_weighted(
        close, entries, exits, raw_config
    )
   
    print("Running Robustness Weighted...")
    strategies["Robustness Weighted"], weights["Robustness Weighted"] = run_strategy_robustness_weighted(
        close, entries, exits, raw_config, robustness
    )
   
    print("Running Buy & Hold Benchmark...")
    strategies["Buy & Hold (EW)"], _ = run_strategy_benchmark(close, raw_config)
   
    # Comparison table
    stats = []
    for name, pf in strategies.items():
        s = pf.stats()
        stats.append({
            "Strategy": name,
            "Total Return [%]": s['Total Return [%]'],
            "Sharpe Ratio": s['Sharpe Ratio'],
            "Sortino Ratio": s['Sortino Ratio'],
            "Max Drawdown [%]": s['Max Drawdown [%]'],
            "Win Rate [%]": s['Win Rate [%]'],
            "Profit Factor": s['Profit Factor'],
            "Expectancy": s['Expectancy'],
            "Total Trades": s['Total Trades']
        })
   
    df_stats = pd.DataFrame(stats)
    df_stats = df_stats.sort_values("Sharpe Ratio", ascending=False)
   
    print("\n--- Strategy Competition Results ---")
    print(df_stats.to_markdown(index=False))
   
    # Save results
    output_dir = Path(args.results_dir) / "portfolio_analysis"
    output_dir.mkdir(exist_ok=True)
    df_stats.to_csv(output_dir / "comparison_stats.csv", index=False)
    
    # Plots
    print("Generating plots...")
    vbt.settings.set_theme('dark')
    
    # Combine values for equity curve comparison
    values = pd.DataFrame({name: pf.value() for name, pf in strategies.items()})
    fig = values.vbt.plot(title="Portfolio Equity Comparison")
    fig.write_html(str(output_dir / "equity_comparison.html"))
    
    # Combined Drawdowns
    drawdowns = pd.DataFrame({name: pf.drawdown() for name, pf in strategies.items()})
    fig_dd = drawdowns.vbt.plot(title="Portfolio Drawdown Comparison")
    fig_dd.write_html(str(output_dir / "drawdown_comparison.html"))
    
    print(f"\nAnalysis complete. Results and plots saved to {output_dir}")
    
    # Export best weights
    best_strat_name = df_stats.iloc[0]["Strategy"]
    if best_strat_name in weights:
        best_weights = weights[best_strat_name]
        # Take the last valid weight for each symbol
        latest_weights = best_weights.iloc[-1].to_dict()
        
        weight_file = output_dir / "portfolio_weights.json"
        with open(weight_file, 'w') as f:
            json.dump({
                "strategy": best_strat_name,
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "weights": latest_weights
            }, f, indent=4)
        print(f"Exported weights for '{best_strat_name}' to {weight_file}")

if __name__ == "__main__":
    main()
